export const USER_NAME = 'USER_NAME';

// auth.js
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// guest.js
export const CHANGE_NAME = 'CHANGE_NAME';
export const GET_VISITED_RESTAURANTS_SUCCESS = 'GET_VISITED_RESTAURANTS_SUCCESS';
export const GET_VISITED_RESTAURANTS_START = 'GET_VISITED_RESTAURANTS_START';
export const GET_VISITED_RESTAURANTS_ERROR = 'GET_VISITED_RESTAURANTS_ERROR';

export const GET_RESTAURANTS_BY_NAME_SUCCESS = 'GET_RESTAURANTS_BY_NAME_SUCCESS';
export const GET_RESTAURANTS_BY_NAME_START = 'GET_RESTAURANTS_BY_NAME_START';
export const GET_RESTAURANTS_BY_NAME_ERROR = 'GET_RESTAURANTS_BY_NAME_ERROR';

// manager.js
export const ADD_EMPLOYEE_STARTED = 'ADD_EMPLOYEE_STARTED';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const ADD_SUPPLIER_STARTED = 'ADD_SUPPLIER_STARTED';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR';


export const ADD_SUPPLY_REQUEST_STARTED = 'ADD_SUPPLY_REQUEST_STARTED';
export const ADD_SUPPLY_REQUEST_SUCCESS = 'ADD_SUPPLY_REQUEST_SUCCESS';
export const ADD_SUPPLY_REQUEST_ERROR = 'ADD_SUPPLY_REQUEST_ERROR';

// supplier.js
export const GET_REQUESTS_STARTED = 'GET_REQUESTS_STARTED';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_ERROR = 'GET_REQUESTS_ERROR';

export const ADD_OFFER_STARTED = 'ADD_OFFER_STARTED';
export const ADD_OFFER_SUCCESS = 'ADD_OFFER_SUCCESS';
export const ADD_OFFER_ERROR = 'ADD_OFFER_ERROR';

//