export const USER_NAME = 'USER_NAME';

// auth.js
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// guest.js
export const CHANGE_NAME = 'CHANGE_NAME';

// manager.js
export const ADD_EMPLOYEE_STARTED = 'ADD_EMPLOYEE_STARTED';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const ADD_SUPPLIER_STARTED = 'ADD_SUPPLIER_STARTED';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR';


export const ADD_SUPPLY_REQUEST_STARTED = 'ADD_SUPPLY_REQUEST_STARTED';
export const ADD_SUPPLY_REQUEST_SUCCESS = 'ADD_SUPPLY_REQUEST_SUCCESS';
export const ADD_SUPPLY_REQUEST_ERROR = 'ADD_SUPPLY_REQUEST_ERROR';

// ?